Repository sopt-makers/sopt-recruiting-frontend, pull requests merged in 2024-08, with the labels that each got.

#332 [Feat] amplitude session replay 추가
  package.json
  src/App.tsx
  src/common/components/Checkbox/index.tsx
  src/common/components/Select/index.tsx
  src/common/components/Textarea/components/Input/index.tsx
  src/views/ApplyPage/components/DefaultSection/index.tsx
  src/views/ApplyPage/components/FileInput/index.tsx
  src/views/dialogs/SubmitDialog/index.tsx
  yarn.lock
Labels: size/L

#334 [Fix] 포트폴리오 파일 형식 제한
  src/views/ApplyPage/components/FileInput/index.tsx
Labels: size/XS

#337 [Chore] GNB 이름 마스킹 처리
  src/common/components/Layout/components/Header/MenuItem/index.tsx
  src/common/components/Layout/components/Header/index.tsx
Labels: size/XS

#339 [Fix] 파일 관련 필수 에러만 제거
  src/views/ApplyPage/components/FileInput/style.css.ts
  src/views/ApplyPage/components/Info/index.tsx
Labels: size/XS

#340 [Deploy] 자잘 수정 사항들 배포
  src/common/components/Layout/components/Header/MenuItem/index.tsx
  src/common/components/Layout/components/Header/index.tsx
  src/views/ApplyPage/components/FileInput/index.tsx
  src/views/ApplyPage/components/FileInput/style.css.ts
  src/views/ApplyPage/components/Info/index.tsx
Labels: size/S

#343 [Feat] CompletePage 사용자 만족도 조사 추가
  src/views/CompletePage/apis.ts
  src/views/CompletePage/components/Survey.tsx
  src/views/CompletePage/hooks/useMutateSatisfaction.ts
  src/views/CompletePage/index.tsx
  src/views/CompletePage/style.css.ts
  src/views/CompletePage/types.ts
Labels: size/L

#347 [Feat] amplitude 허수 판독기
  src/views/SignedInPage/index.tsx
  src/views/SignupPage/hooks/useMutateSignUp.tsx
Labels: size/XS

#348 [Fix] 지원 완료 이메일 템플릿 깨짐 해결
  src/views/email/complete.html
Labels: size/S

#353 [Fix] 이메일 인증 버튼 크기 깨지는 에러 해결
  src/common/components/Input/components/InputButton/style.css.ts
Labels: size/XS

#356 [Fix] 분 단위 추가
  src/views/ApplyPage/components/ApplyInfo/index.tsx
Labels: size/S

#346 [Feat] 헤더 스크롤 시 숨김 처리
  src/common/hooks/useScrollPosition.tsx
  src/views/ApplyPage/components/ApplyCategory/index.tsx
  src/views/ApplyPage/components/ApplyCategory/style.css.ts
  src/views/ApplyPage/components/CommonSection/style.css.ts
  src/views/ApplyPage/components/PartSection/style.css.ts
  src/views/ApplyPage/style.css.ts
Labels: size/M

#354 [Design] Mobile ver. - 로그인, 비밀번호 페이지 구현
  package.json
  src/App.tsx
  src/common/components/Button/index.tsx
  src/common/components/Button/style.css.ts
  src/common/components/Callout/index.tsx
  src/common/components/Callout/style.css.ts
  src/common/components/Input/components/Description/index.tsx
  src/common/components/Input/components/Description/style.css.ts
  src/common/components/Input/components/InputButton/index.tsx
  src/common/components/Input/components/InputButton/style.css.ts
  src/common/components/Input/components/InputLine/index.tsx
  src/common/components/Input/components/InputLine/style.css.ts
  src/common/components/Input/components/InputTheme/index.tsx
  src/common/components/Input/components/InputTheme/style.css.ts
  src/common/components/Input/components/TextBox/index.tsx
  src/common/components/Input/components/TextBox/style.css.ts
  src/common/components/Input/components/Timer/index.tsx
  src/common/components/Input/components/Timer/style.css.ts
  src/common/components/Input/constants.ts
  src/common/components/Input/style.css.ts
  src/common/components/Input/types.ts
  src/common/components/Layout/components/Header/style.css.ts
  src/common/components/Layout/style.css.ts
  src/common/components/Title/index.tsx
  src/common/components/Title/style.css.ts
  src/common/hooks/useDevice.ts
  src/views/PasswordPage/index.tsx
  src/views/PasswordPage/style.css.ts
  src/views/SignInPage/components/SignInInfo/index.tsx
  src/views/SignInPage/components/SignInInfo/style.css.ts
  src/views/SignInPage/index.tsx
  src/views/SignInPage/style.css.ts
  yarn.lock
Labels: size/L

#360 [Fix] 23:59에 지원서 마감되는 에러 해결
  src/views/ApplyPage/components/ApplyInfo/index.tsx
Labels: size/XS

#362 [Fix] apply page 카테고리 관련 에러 해결
  src/views/ApplyPage/components/ApplyCategory/index.tsx
  src/views/ApplyPage/components/ApplyCategory/style.css.ts
  src/views/ApplyPage/index.tsx
  src/views/ReviewPage/index.tsx
Labels: size/S

#364 [Fix] apply info 공백 제거
  src/views/ApplyPage/components/ApplyInfo/index.tsx
Labels: size/XS

#366 [Fix] 프로필 사진 undefined로 서버에 전송되는 이슈 해결
  package.json
  src/views/ApplyPage/components/DefaultSection/index.tsx
  src/views/ApplyPage/index.tsx
  yarn.lock
Labels: size/L

#368 [Fix] 사진과 체크박스의 필수 여부 체크할 때 발생되는 에러 해결
  src/common/components/Checkbox/index.tsx
  src/views/ApplyPage/index.tsx
Labels: size/S

#371 [Design] Mobile ver. - Header 반응형 구현
  src/common/assets/MakersDarkLogo.tsx
  src/common/assets/MakersLogo.tsx
  src/common/assets/NowsoptLogo.tsx
  src/common/components/Input/components/InputTheme/index.tsx
  src/common/components/Layout/components/Header/MenuItem/style.css.ts
  src/common/components/Layout/components/Header/Nav/MenuItem/index.tsx
  src/common/components/Layout/components/Header/Nav/MenuItem/style.css.ts
  src/common/components/Layout/components/Header/Nav/MenuList/index.tsx
  src/common/components/Layout/components/Header/Nav/MenuList/style.css.ts
  src/common/components/Layout/components/Header/Nav/index.tsx
  src/common/components/Layout/components/Header/Nav/style.css.ts
  src/common/components/Layout/components/Header/index.tsx
  src/common/components/Layout/components/Header/style.css.ts
  src/common/components/Layout/style.css.ts
  src/common/components/Select/style.css.ts
  src/common/constants/zIndex.ts
  src/styles/animation.css.ts
  src/styles/theme.css.ts
  src/views/ApplyPage/components/FileInput/style.css.ts
Labels: size/XL

#373 [Design] Mobile ver. - MyPage 구현
  src/views/MyPage/index.tsx
  src/views/MyPage/style.css.ts
  src/views/SignedInPage/index.tsx
Labels: size/L

#370 [Design] Mobile ver. - 결과 페이지 반응형
  src/common/constants/zIndex.ts
  src/views/MyPage/index.tsx
  src/views/ResultPage/components/FinalResult.tsx
  src/views/ResultPage/components/ScreeningResult.tsx
  src/views/ResultPage/components/style.css.ts
  src/views/SignedInPage/index.tsx
Labels: size/L

#380 [Deploy] 모바일 접속 미지원 해제 및 일부 반응형 작업 배포
  src/common/assets/MakersDarkLogo.tsx
  src/common/assets/MakersLogo.tsx
  src/common/assets/NowsoptLogo.tsx
  src/common/components/Input/components/InputTheme/index.tsx
  src/common/components/Layout/components/Header/MenuItem/style.css.ts
  src/common/components/Layout/components/Header/Nav/MenuItem/index.tsx
  src/common/components/Layout/components/Header/Nav/MenuItem/style.css.ts
  src/common/components/Layout/components/Header/Nav/MenuList/index.tsx
  src/common/components/Layout/components/Header/Nav/MenuList/style.css.ts
  src/common/components/Layout/components/Header/Nav/index.tsx
  src/common/components/Layout/components/Header/Nav/style.css.ts
  src/common/components/Layout/components/Header/index.tsx
  src/common/components/Layout/components/Header/style.css.ts
  src/common/components/Layout/style.css.ts
  src/common/components/Select/style.css.ts
  src/common/constants/zIndex.ts
  src/styles/animation.css.ts
  src/styles/theme.css.ts
  src/views/ApplyPage/components/FileInput/style.css.ts
  src/views/MyPage/index.tsx
  src/views/MyPage/style.css.ts
  src/views/ResultPage/components/FinalResult.tsx
  src/views/ResultPage/components/ScreeningResult.tsx
  src/views/ResultPage/components/style.css.ts
Labels: size/XXL

#384 [Fix] 결과페이지 폼링크 앞에 false 잘못들어가는 이슈
  src/views/ResultPage/components/FinalResult.tsx
  src/views/ResultPage/components/ScreeningResult.tsx
Labels: size/XS

#387 [Fix] 제출 기한 지나면 제출 못하도록 막기
  src/views/ApplyPage/index.tsx
  src/views/dialogs/PreventApplyDialog/index.tsx
Labels: size/M

#389 [Design] Mobile ver. - SignupPage 구현
  src/views/SignInPage/components/SignInInfo/style.css.ts
  src/views/SignupPage/index.tsx
  src/views/SignupPage/style.css.ts
Labels: size/M

#388 [Design] Mobile ver. - ErrorPage 구현
  src/views/CompletePage/style.css.ts
  src/views/ErrorPage/components/ErrorCode/index.tsx
  src/views/ErrorPage/components/ErrorCode/style.css.ts
  src/views/ErrorPage/components/NoMore/index.tsx
  src/views/ErrorPage/index.tsx
  src/views/ErrorPage/style.css.ts
  src/views/loadings/BigLoding/style.css.ts
Labels: size/L

#391 [Fix] useDevice hook 확장
  src/common/hooks/useDevice.ts
Labels: size/S

#394 [Fix] 햄버거 메뉴 토글 z index 높이기
  src/common/constants/zIndex.ts
Labels: size/XS

#397 [Feat] session replay masking 추가
  src/common/components/Select/index.tsx
  src/common/components/Textarea/components/Input/index.tsx
  src/views/ApplyPage/components/FileInput/index.tsx
  src/views/MyPage/index.tsx
  src/views/ResultPage/components/FinalResult.tsx
  src/views/ResultPage/components/ScreeningResult.tsx
Labels: size/M

#396 [Design] Mobile ver. - 공통 컴포넌트
  src/common/components/Button/index.tsx
  src/common/components/Callout/index.tsx
  src/common/components/Input/components/Description/index.tsx
  src/common/components/Input/components/InputButton/index.tsx
  src/common/components/Input/components/InputLine/index.tsx
  src/common/components/Input/components/InputLine/style.css.ts
  src/common/components/Input/components/InputTheme/index.tsx
  src/common/components/Input/components/TextBox/index.tsx
  src/common/components/Input/components/Timer/index.tsx
  src/common/components/Layout/components/Footer/index.tsx
  src/common/components/Layout/components/Footer/style.css.ts
  src/common/components/Select/index.tsx
  src/common/components/Select/style.css.ts
  src/common/components/Textarea/components/Input/index.tsx
  src/common/components/Textarea/components/Input/style.css.ts
  src/common/components/Textarea/components/Label/index.tsx
  src/common/components/Textarea/components/Label/style.css.ts
  src/common/components/Title/index.tsx
  src/common/hooks/useDevice.ts
  src/views/ApplyPage/index.tsx
  src/views/PasswordPage/index.tsx
  src/views/SignInPage/components/SignInInfo/index.tsx
  src/views/SignInPage/index.tsx
Labels: size/L

#392 [Design] Mobile ver. - Dialog 구현
  src/App.tsx
  src/common/components/Dialog/index.tsx
  src/common/components/Dialog/style.css.ts
  src/views/ApplyPage/index.tsx
  src/views/ReviewPage/index.tsx
  src/views/SignupPage/components/SignupForm/index.tsx
  src/views/dialogs/CompleteDialog/index.tsx
  src/views/dialogs/DraftDialog/index.tsx
  src/views/dialogs/ExistingApplicantDialog/index.tsx
  src/views/dialogs/ExitDialog/index.tsx
  src/views/dialogs/PreventApplyDialog/index.tsx
  src/views/dialogs/PreventReviewDialog/index.tsx
  src/views/dialogs/SessionExpiredDialog/index.tsx
  src/views/dialogs/SubmitDialog/index.tsx
  src/views/dialogs/SubmitDialog/style.css.ts
  src/views/dialogs/index.tsx
  src/views/dialogs/style.css.ts
Labels: size/L

#399 [Fix] build 에러 잡기
  src/common/components/Input/components/InputTheme/index.tsx
Labels: size/XS

#401 [Design] Mobile ver. - ApplyPage, ReviewPage 구현
  .gitignore
  src/App.tsx
  src/common/components/Dialog/index.tsx
  src/views/ApplyPage/components/ApplyCategory/index.tsx
  src/views/ApplyPage/components/ApplyCategory/style.css.ts
  src/views/ApplyPage/components/ApplyHeader/index.tsx
  src/views/ApplyPage/components/ApplyHeader/style.css.ts
  src/views/ApplyPage/components/ApplyInfo/index.tsx
  src/views/ApplyPage/components/ApplyInfo/style.css.ts
  src/views/ApplyPage/components/BottomSection/index.tsx
  src/views/ApplyPage/components/BottomSection/style.css.ts
  src/views/ApplyPage/components/CommonSection/index.tsx
  src/views/ApplyPage/components/CommonSection/style.css.ts
  src/views/ApplyPage/components/DefaultSection/index.tsx
  src/views/ApplyPage/components/DefaultSection/style.css.ts
  src/views/ApplyPage/components/FileInput/index.tsx
  src/views/ApplyPage/components/FileInput/style.css.ts
  src/views/ApplyPage/components/Info/index.tsx
  src/views/ApplyPage/components/Info/style.css.ts
  src/views/ApplyPage/components/LinkInput/index.tsx
  src/views/ApplyPage/components/LinkInput/style.css.ts
  src/views/ApplyPage/components/PartSection/index.tsx
  src/views/ApplyPage/components/PartSection/style.css.ts
  src/views/ApplyPage/index.tsx
  src/views/ApplyPage/style.css.ts
  src/views/ReviewPage/index.tsx
  src/views/dialogs/CompleteDialog/index.tsx
  src/views/dialogs/DraftDialog/index.tsx
  src/views/dialogs/ExistingApplicantDialog/index.tsx
  src/views/dialogs/ExitDialog/index.tsx
  src/views/dialogs/PreventApplyDialog/index.tsx
  src/views/dialogs/PreventReviewDialog/index.tsx
  src/views/dialogs/SessionExpiredDialog/index.tsx
  src/views/dialogs/SubmitDialog/index.tsx
Labels: size/XXL

#403 [Fix] meta tag && 연산자 삭제
  index.html
  src/common/components/Layout/index.tsx
Labels: size/S

#404 [Fix] ReviewPage 클릭 비활성화 처리
  src/common/components/Checkbox/index.tsx
  src/common/components/Checkbox/style.css.ts
  src/common/components/Radio/components/Option/style.css.ts
  src/views/ApplyPage/components/BottomSection/index.tsx
Labels: size/M

#405 [Fix] 스크롤 초기화
  src/common/components/Layout/components/Settings/Head.tsx
  src/common/components/Layout/components/Settings/ScrollToTop.tsx
  src/common/components/Layout/index.tsx
Labels: size/L

#407 [Fix] 누락되어있는 SOPT ver. ApplyInfo 추가
  src/views/ApplyPage/constant.ts
Labels: size/S

#409 [Fix] 전체화면 권장 제거
  src/views/MyPage/index.tsx
Labels: size/S

#411 [Fix] deviceType undefined 에러 뜨는 이슈 해결
  src/App.tsx
  src/common/components/Button/index.tsx
  src/common/components/Callout/index.tsx
  src/common/components/Dialog/index.tsx
  src/common/components/Input/components/Description/index.tsx
  src/common/components/Input/components/InputButton/index.tsx
  src/common/components/Input/components/InputLine/index.tsx
  src/common/components/Input/components/InputTheme/index.tsx
  src/common/components/Input/components/TextBox/index.tsx
  src/common/components/Input/components/Timer/index.tsx
  src/common/components/Layout/components/Header/Nav/MenuItem/index.tsx
  src/common/components/Layout/components/Header/Nav/MenuList/index.tsx
  src/common/components/Layout/components/Header/Nav/index.tsx
  src/common/components/Layout/components/Header/index.tsx
  src/common/components/Select/index.tsx
  src/common/components/Textarea/components/Input/index.tsx
  src/common/components/Textarea/components/Label/index.tsx
  src/common/components/Title/index.tsx
  src/common/store/deviceTypeContext.ts
  src/views/ApplyPage/components/ApplyCategory/index.tsx
  src/views/ApplyPage/components/ApplyHeader/index.tsx
  src/views/ApplyPage/components/ApplyInfo/index.tsx
  src/views/ApplyPage/components/BottomSection/index.tsx
  src/views/ApplyPage/components/CommonSection/index.tsx
  src/views/ApplyPage/components/DefaultSection/index.tsx
  src/views/ApplyPage/components/FileInput/index.tsx
  src/views/ApplyPage/components/Info/index.tsx
  src/views/ApplyPage/components/LinkInput/index.tsx
  src/views/ApplyPage/components/PartSection/index.tsx
  src/views/ApplyPage/index.tsx
  src/views/CompletePage/components/Survey.tsx
  src/views/CompletePage/index.tsx
  src/views/ErrorPage/components/ErrorCode/index.tsx
  src/views/ErrorPage/components/NoMore/index.tsx
  src/views/ErrorPage/index.tsx
  src/views/MyPage/index.tsx
  src/views/PasswordPage/index.tsx
  src/views/ResultPage/components/FinalResult.tsx
  src/views/ResultPage/components/ScreeningResult.tsx
  src/views/ReviewPage/index.tsx
  src/views/SignInPage/components/SignInInfo/index.tsx
  src/views/SignInPage/index.tsx
  src/views/SignupPage/index.tsx
  src/views/dialogs/CompleteDialog/index.tsx
  src/views/dialogs/DraftDialog/index.tsx
  src/views/dialogs/ExistingApplicantDialog/index.tsx
  src/views/dialogs/ExitDialog/index.tsx
  src/views/dialogs/PreventApplyDialog/index.tsx
  src/views/dialogs/PreventReviewDialog/index.tsx
  src/views/dialogs/SessionExpiredDialog/index.tsx
  src/views/dialogs/SubmitDialog/index.tsx
Labels: size/L

#413 [Chore] 파트 제약 제거
  src/views/ApplyPage/components/PartSection/index.tsx
Labels: size/XS

#414 [Fix] 동적 메타태그 하드코딩으로 수정
  index.html
  makersManifest.webmanifest
  manifest.webmanifest
  package.json
  src/common/components/Layout/index.tsx
  yarn.lock
Labels: size/M

#416 [Fix] 체크박스 선택 안 되는 에러 해결
  src/common/components/Checkbox/index.tsx
Labels: size/XS

#417 [Deploy] 배포
  index.html
  makersManifest.webmanifest
  manifest.webmanifest
  package.json
  src/App.tsx
  src/common/components/Button/index.tsx
  src/common/components/Callout/index.tsx
  src/common/components/Checkbox/index.tsx
  src/common/components/Dialog/index.tsx
  src/common/components/Input/components/Description/index.tsx
  src/common/components/Input/components/InputButton/index.tsx
  src/common/components/Input/components/InputLine/index.tsx
  src/common/components/Input/components/InputTheme/index.tsx
  src/common/components/Input/components/TextBox/index.tsx
  src/common/components/Input/components/Timer/index.tsx
  src/common/components/Layout/components/Head.tsx
  src/common/components/Layout/components/Header/Nav/MenuItem/index.tsx
  src/common/components/Layout/components/Header/Nav/MenuList/index.tsx
  src/common/components/Layout/components/Header/Nav/index.tsx
  src/common/components/Layout/components/Header/index.tsx
  src/common/components/Layout/index.tsx
  src/common/components/Select/index.tsx
  src/common/components/Textarea/components/Input/index.tsx
  src/common/components/Textarea/components/Label/index.tsx
  src/common/components/Title/index.tsx
  src/common/store/deviceTypeContext.ts
  src/views/ApplyPage/components/ApplyCategory/index.tsx
  src/views/ApplyPage/components/ApplyHeader/index.tsx
  src/views/ApplyPage/components/ApplyInfo/index.tsx
  src/views/ApplyPage/components/BottomSection/index.tsx
  src/views/ApplyPage/components/CommonSection/index.tsx
  src/views/ApplyPage/components/DefaultSection/index.tsx
  src/views/ApplyPage/components/FileInput/index.tsx
  src/views/ApplyPage/components/Info/index.tsx
  src/views/ApplyPage/components/LinkInput/index.tsx
  src/views/ApplyPage/components/PartSection/index.tsx
  src/views/ApplyPage/index.tsx
  src/views/CompletePage/components/Survey.tsx
  src/views/CompletePage/index.tsx
  src/views/ErrorPage/components/ErrorCode/index.tsx
  src/views/ErrorPage/components/NoMore/index.tsx
  src/views/ErrorPage/index.tsx
  src/views/MyPage/index.tsx
  src/views/PasswordPage/index.tsx
  src/views/ResultPage/components/FinalResult.tsx
  src/views/ResultPage/components/ScreeningResult.tsx
  src/views/ReviewPage/index.tsx
  src/views/SignInPage/components/SignInInfo/index.tsx
  src/views/SignInPage/index.tsx
  src/views/SignupPage/index.tsx
  src/views/dialogs/CompleteDialog/index.tsx
  src/views/dialogs/DraftDialog/index.tsx
  src/views/dialogs/ExistingApplicantDialog/index.tsx
  src/views/dialogs/ExitDialog/index.tsx
  src/views/dialogs/PreventApplyDialog/index.tsx
  src/views/dialogs/PreventReviewDialog/index.tsx
  src/views/dialogs/SessionExpiredDialog/index.tsx
  src/views/dialogs/SubmitDialog/index.tsx
  yarn.lock
Labels: size/L

#419 [Fix] manifest 및 og tag link 수정
  index.html
Labels: size/S

#421 [Fix] Og 이미지 파일명 오탈자 수정
  index.html
  public/makersOg.png
Labels: size/S

#424 [Fix] main title word break 설정
  src/common/components/Title/style.css.ts
Labels: size/XS

#428 [Fix] 만족도 조사 제출 1회만 허용
  src/views/CompletePage/components/Survey.tsx
Labels: size/XS

#429 [Fix] 텍스트필드 모바일뷰 폰트 사이즈 14->16px 수정
  src/common/components/Input/components/InputLine/index.tsx
  src/common/components/Input/components/InputLine/style.css.ts
Labels: size/S

#430 [Deploy] NPS, mobile font size 수정
  src/common/components/Input/components/InputLine/index.tsx
  src/common/components/Input/components/InputLine/style.css.ts
  src/views/CompletePage/components/Survey.tsx
Labels: size/M

#434 [Refactor] 번들 크기 개선 - 1
  package.json
  src/views/loadings/BigLoding/index.tsx
  src/views/loadings/ButtonLoading/index.tsx
  src/views/loadings/Lottie/index.tsx
  src/views/loadings/SmallLoading/index.tsx
  src/views/loadings/lotties/mainLoading.json
  vite.config.ts
  yarn.lock
Labels: size/XXL

#435 [Refactor] 번들 크기 개선 - 2
  src/common/apis/tokenInstance.ts
  src/common/components/Input/components/Timer/index.tsx
  src/common/hooks/useDate.tsx
  src/views/ApplyPage/components/ApplyInfo/index.tsx
  src/views/ResultPage/components/FinalResult.tsx
  src/views/ResultPage/components/ScreeningResult.tsx
Labels: size/S

#432 [Refactor] 번들 크기 개선 - 3
  src/App.tsx
  src/views/ApplyPage/index.tsx
  src/views/MyPage/index.tsx
  src/views/PasswordPage/components/PasswordForm/index.tsx
  src/views/PasswordPage/index.tsx
  src/views/ResultPage/index.tsx
  src/views/ReviewPage/index.tsx
  src/views/SignInPage/index.tsx
  src/views/SignupPage/components/SignupForm/index.tsx
  src/views/SignupPage/index.tsx
  vite.config.ts
Labels: size/M
