Repository sopt-makers/sopt-recruiting-frontend, pull requests merged in 2024-07, with the labels that each got.

#88 [Fix] 500에러 페이지 뒤로가기 navigation
  src/views/ErrorPage/index.tsx
Labels: size/S

#89 [Fix] /sign-up 페이지 오류
  src/common/components/Input/InputButton/index.tsx
  src/common/components/Input/InputButton/style.css.ts
  src/views/SignupPage/index.tsx
Labels: size/S

#86 [Design] 로딩 페이지 퍼블리싱
  package.json
  src/common/components/Button/index.tsx
  src/common/components/Callout/index.tsx
  src/common/components/Input/InputButton/index.tsx
  src/common/components/Input/types.ts
  src/views/CompletePage/index.tsx
  src/views/loadings/BigLoding/index.tsx
  src/views/loadings/BigLoding/style.css.ts
  src/views/loadings/ButtonLoading/index.tsx
  src/views/loadings/SmallLoading/index.tsx
  src/views/loadings/SmallLoading/style.css.ts
  src/views/loadings/lotties/buttonLoadingWhite.json
  src/views/loadings/lotties/mainLoading.json
  yarn.lock
Labels: size/XXL

#87 [Feat] 주소 검색 api 연동
  index.html
  src/views/ApplyPage/components/DefaultSection/components/Postcode/index.tsx
  src/views/ApplyPage/components/DefaultSection/index.tsx
Labels: size/M

#96 [Feat] 제출 확인 dialog에서 checkbox 클릭에 따른 버튼 disabled 상태 변화
  src/common/components/Button/style.css.ts
  src/common/components/Input/InputLine/style.css.ts
  src/common/components/Layout/Header/MenuItem/style.css.ts
  src/common/components/Select/style.css.ts
  src/common/components/Textarea/Input/style.css.ts
  src/views/ApplyPage/components/FileInput/style.css.ts
  src/views/MainPage/index.tsx
  src/views/dialogs/SubmitDialog/index.tsx
  src/views/dialogs/style.css.ts
Labels: size/M

#100 [Chore] label과 input 연결
  src/common/components/Select/index.tsx
  src/common/components/Select/style.css.ts
  src/common/components/Textarea/Label/index.tsx
  src/views/ApplyPage/components/DefaultSection/index.tsx
Labels: size/S

#92 [Fix] 헤더 스크롤 안 되는 에러 해결
  src/common/components/Layout/Header/style.css.ts
  src/common/components/Layout/style.css.ts
Labels: size/XS

#90 [Feat] 헤더 네비게이션 링크 연결
  src/common/components/Layout/Header/MenuItem/index.tsx
  src/common/components/Layout/Header/contants.ts
  src/common/components/Layout/Header/index.tsx
Labels: size/S

#102 [Chore] 자잘 에러 수정
  src/App.tsx
  src/common/components/Layout/Header/MenuItem/style.css.ts
  src/views/ApplyPage/components/ApplyHeader/style.css.ts
  src/views/TestPage/index.tsx
Labels: size/M

#99 [Design] Textarea 내 Link 컴포넌트 생성
  src/common/components/Textarea/Label/style.css.ts
  src/common/components/Textarea/index.tsx
  src/common/components/Textarea/style.css.ts
  src/views/ApplyPage/components/LinkInput/index.tsx
  src/views/ApplyPage/components/LinkInput/style.css.ts
  src/views/ApplyPage/components/PartSection/constants.ts
  src/views/ApplyPage/components/PartSection/index.tsx
  src/views/ApplyPage/components/PartSection/types.ts
  src/views/ApplyPage/index.tsx
Labels: size/L

#104 [Feat] 새 지원서 작성하기 api 연동
  src/common/apis/instance.ts
  src/common/components/Input/InputTheme.tsx
  src/common/components/Input/apis.ts
  src/common/components/Input/style.css.ts
  src/common/components/Input/types.ts
  src/common/constants/validationCheck.ts
  src/views/SignupPage/apis.ts
  src/views/SignupPage/hooks/.gitkeep
  src/views/SignupPage/index.tsx
  src/views/SignupPage/types.ts
  tsconfig.json
  vite.config.ts
Labels: size/L

#107 [Feat] 로그인 api 연동
  src/App.tsx
  src/common/components/Layout/Header/contants.ts
  src/common/components/Layout/Header/index.tsx
  src/common/constants/validationCheck.ts
  src/views/MainPage/hooks/.gitkeep
  src/views/MainPage/index.tsx
  src/views/SignInPage/apis.ts
  src/views/SignInPage/index.tsx
  src/views/SignInPage/style.css.ts
  src/views/SignInPage/types.ts
Labels: size/L

#109 [Feat] 비밀번호 재설정 api 연동
  src/common/components/Input/InputTheme.tsx
  src/common/components/Input/apis.ts
  src/common/components/Input/types.ts
  src/common/constants/validationCheck.ts
  src/common/hooks/.gitkeep
  src/common/hooks/useVerificationStatus.tsx
  src/views/PasswordPage/apis.ts
  src/views/PasswordPage/index.tsx
  src/views/PasswordPage/types.ts
  src/views/SignupPage/index.tsx
Labels: size/L

#110 [Fix] 타이머 초기화 에러 수정
  src/common/components/Input/InputTheme.tsx
  src/common/components/Input/Timer/index.tsx
Labels: size/S

#113 [Feat] 마이 페이지 api 연동
  src/common/apis/tokenInstance.ts
  src/views/MyPage/apis.ts
  src/views/MyPage/index.tsx
  src/views/MyPage/types.ts
Labels: size/L

#116 [Feat] 임시저장 api 연동
  src/common/components/Input/InputLine/index.tsx
  src/common/components/Input/InputLine/style.css.ts
  src/common/components/Select/index.tsx
  src/common/components/Select/style.css.ts
  src/common/constants/styleValues.ts
  src/views/ApplyPage/apis.ts
  src/views/ApplyPage/components/ApplyHeader/index.tsx
  src/views/ApplyPage/components/BottomSection/index.tsx
  src/views/ApplyPage/components/DefaultSection/components/Postcode/index.tsx
  src/views/ApplyPage/components/DefaultSection/index.tsx
  src/views/ApplyPage/components/PartSection/index.tsx
  src/views/ApplyPage/index.tsx
  src/views/ApplyPage/types.ts
Labels: size/L

#120 [Feat] 페이지 이탈 시 dialog 표시
  src/views/ApplyPage/index.tsx
Labels: size/XS

#121 [Feat] validation 추가
  src/common/constants/validationCheck.ts
  src/views/ApplyPage/components/DefaultSection/index.tsx
Labels: size/M

#127 [Feat] common, part section 임시 저장 구현
  src/common/components/Input/InputLine/index.tsx
  src/common/components/Radio/index.tsx
  src/common/components/Select/index.tsx
  src/views/ApplyPage/components/BottomSection/index.tsx
  src/views/ApplyPage/components/CommonSection/index.tsx
  src/views/ApplyPage/components/DefaultSection/index.tsx
  src/views/ApplyPage/components/PartSection/index.tsx
  src/views/ApplyPage/index.tsx
  src/views/ApplyPage/types.ts
Labels: size/L

#124 [Fix] QA 반영
  src/views/ApplyPage/components/DefaultSection/constants.ts
  src/views/loadings/BigLoding/style.css.ts
Labels: size/XS

#126 [Feat] 질문 리스트 받아오기
  src/common/components/Radio/index.tsx
  src/views/ApplyPage/apis.ts
  src/views/ApplyPage/components/BottomSection/index.tsx
  src/views/ApplyPage/components/CommonSection/constants.ts
  src/views/ApplyPage/components/CommonSection/index.tsx
  src/views/ApplyPage/components/DefaultSection/index.tsx
  src/views/ApplyPage/components/PartSection/index.tsx
  src/views/ApplyPage/index.tsx
  src/views/ApplyPage/types.ts
Labels: size/L

#130 [Fix] merge 과정에서 생긴 에러 해결 및 QA
  src/App.tsx
  src/common/components/Input/InputTheme.tsx
  src/common/constants/validationCheck.ts
  src/views/ApplyPage/components/DefaultSection/index.tsx
  src/views/ApplyPage/index.tsx
  src/views/SignInPage/index.tsx
  src/views/SignupPage/index.tsx
Labels: size/L

#133 [Build] 빌드 에러 잡기
  package.json
  src/views/ApplyPage/components/DefaultSection/components/Postcode/index.tsx
  src/views/ReviewPage/style.css.ts
  yarn.lock
Labels: size/S

#137 [Feat] 제출하기 api 연동
  src/common/components/Input/types.ts
  src/common/constants/defaultValues.ts
  src/views/ApplyPage/apis.ts
  src/views/ApplyPage/index.tsx
  src/views/ApplyPage/types.ts
  src/views/dialogs/SubmitDialog/index.tsx
  src/views/loadings/ButtonLoading/index.tsx
Labels: size/L

#139 [Fix] 지원서 작성 페이지에서 오류 메세지로 자동 스크롤 안 되는 오류 수정
  src/views/ApplyPage/components/BottomSection/index.tsx
  src/views/ApplyPage/index.tsx
Labels: size/M

#140 [Fix] Intersection Observer threshold 수정
  src/views/ApplyPage/components/ApplyCategory/constant.ts
  src/views/ApplyPage/components/ApplyCategory/index.tsx
  src/views/ApplyPage/components/CommonSection/index.tsx
  src/views/ApplyPage/components/CommonSection/style.css.ts
  src/views/ApplyPage/components/DefaultSection/index.tsx
  src/views/ApplyPage/components/DefaultSection/style.css.ts
  src/views/ApplyPage/components/PartSection/index.tsx
  src/views/ApplyPage/components/PartSection/style.css.ts
  src/views/ApplyPage/hooks/useIntersectionObserver.ts
  src/views/ApplyPage/index.tsx
  src/views/ApplyPage/style.css.ts
Labels: size/L

#142 [Fix] 1차 QA 하기
  src/common/components/Callout/index.tsx
  src/common/components/Callout/style.css.ts
  src/common/components/Input/InputLine/index.tsx
  src/common/components/Input/InputTheme.tsx
  src/common/components/Layout/Header/MenuItem/index.tsx
  src/common/components/Layout/Header/MenuItem/style.css.ts
  src/common/components/Layout/Header/index.tsx
  src/common/components/Layout/Header/style.css.ts
  src/views/ApplyPage/components/DefaultSection/constants.ts
  src/views/ApplyPage/index.tsx
  src/views/PasswordPage/index.tsx
  src/views/SignInPage/index.tsx
  src/views/SignInPage/style.css.ts
  src/views/SignupPage/index.tsx
Labels: size/L

#146 [Feat] 최신기수 조회 api 연동
  package.json
  src/common/store/userInfoContext.ts
  src/views/ApplyPage/components/ApplyInfo/index.tsx
  src/views/ApplyPage/constant.ts
  src/views/ApplyPage/index.tsx
  src/views/MainPage/apis.ts
  src/views/MainPage/index.tsx
  src/views/MainPage/types.ts
  yarn.lock
Labels: size/L

#148 [Refactor] 변수명, 타입 통일
  src/common/components/Checkbox/index.tsx
  src/common/components/Input/InputLine/index.tsx
  src/common/components/Input/InputLine/utils/validatePasswordConfirm.ts
  src/common/components/Input/InputTheme.tsx
  src/common/components/Input/TextBox/index.tsx
  src/common/components/Input/types.ts
  src/common/components/Select/index.tsx
  src/common/components/Select/type.ts
  src/common/components/Textarea/Input/index.tsx
  src/common/components/Textarea/index.tsx
  src/views/ApplyPage/components/BottomSection/index.tsx
  src/views/ApplyPage/components/CommonSection/index.tsx
  src/views/ApplyPage/components/DefaultSection/components/Postcode/index.tsx
  src/views/ApplyPage/components/DefaultSection/index.tsx
  src/views/ApplyPage/components/PartSection/index.tsx
  src/views/ApplyPage/index.tsx
  src/views/PasswordPage/index.tsx
  src/views/SignInPage/index.tsx
  src/views/SignupPage/index.tsx
Labels: size/L

#150 [Fix] 2차 QA
  index.html
  src/App.tsx
  src/common/apis/getRecruitingInfo.ts
  src/common/apis/tokenInstance.ts
  src/common/components/Input/InputTheme.tsx
  src/common/components/Input/apis.ts
  src/common/components/Input/types.ts
  src/common/components/Layout/Header/contants.ts
  src/common/components/Layout/Header/index.tsx
  src/common/components/Select/index.tsx
  src/common/hooks/use.tsx
  src/common/store/recruitingInfoContext.ts
  src/common/type/types.ts
  src/views/ApplyPage/components/ApplyHeader/index.tsx
  src/views/ApplyPage/components/ApplyInfo/index.tsx
  src/views/ApplyPage/components/ApplyInfo/style.css.ts
  src/views/ApplyPage/components/BottomSection/index.tsx
  src/views/ApplyPage/components/BottomSection/style.css.ts
  src/views/ApplyPage/components/DefaultSection/index.tsx
  src/views/ApplyPage/constant.ts
  src/views/ApplyPage/index.tsx
  src/views/ErrorPage/index.tsx
  src/views/MainPage/index.tsx
  src/views/PasswordPage/index.tsx
  src/views/SignInPage/index.tsx
  src/views/SignInPage/style.css.ts
  src/views/SignupPage/index.tsx
  src/views/dialogs/SessionExpiredDialog/index.tsx
  src/views/dialogs/SubmitDialog/index.tsx
  src/views/email/auth.html
  src/views/email/complete.html
  tsconfig.json
  vite.config.ts
Labels: size/XL

#151 [Refactor] useQuery, useMutate 파일 분리
  src/common/hooks/useGetRecruitingInfo.tsx
  src/views/ApplyPage/hooks/useGetDraft.tsx
  src/views/ApplyPage/hooks/useGetQuestions.tsx
  src/views/ApplyPage/hooks/useMutateDraft.tsx
  src/views/ApplyPage/hooks/useMutateSubmit.tsx
  src/views/ApplyPage/index.tsx
  src/views/MainPage/index.tsx
  src/views/MyPage/hooks/useGetMyInfo.tsx
  src/views/MyPage/index.tsx
  src/views/PasswordPage/apis.ts
  src/views/PasswordPage/hooks/useMutateChangePassword.tsx
  src/views/PasswordPage/index.tsx
  src/views/SignInPage/apis.ts
  src/views/SignInPage/hooks/useMutateSignIn.tsx
  src/views/SignInPage/index.tsx
  src/views/SignupPage/apis.ts
  src/views/SignupPage/hooks/useMutateSignUp.tsx
  src/views/SignupPage/index.tsx
Labels: size/L

#154 Feat/#152 after submita[Feat] 제출 완료 후 flow 구현
  src/App.tsx
  src/views/ApplyPage/apis.ts
  src/views/ApplyPage/components/ApplyHeader/index.tsx
  src/views/ApplyPage/components/ApplyInfo/index.tsx
  src/views/ApplyPage/components/BottomSection/index.tsx
  src/views/ApplyPage/components/CommonSection/index.tsx
  src/views/ApplyPage/components/DefaultSection/components/Postcode/index.tsx
  src/views/ApplyPage/components/DefaultSection/index.tsx
  src/views/ApplyPage/components/DefaultSection/style.css.ts
  src/views/ApplyPage/components/PartSection/index.tsx
  src/views/ApplyPage/hooks/useMutateSubmit.tsx
  src/views/ApplyPage/index.tsx
  src/views/ApplyPage/types.ts
  src/views/CompletePage/index.tsx
  src/views/MainPage/index.tsx
  src/views/MyPage/index.tsx
  src/views/ReviewPage/components/.gitkeep
  src/views/ReviewPage/hooks/.gitkeep
  src/views/ReviewPage/index.tsx
  src/views/SignedInPage/apis.ts
  src/views/SignedInPage/hooks/useGetDraft.tsx
  src/views/SignedInPage/index.tsx
Labels: size/L

#156 [Feat] 결과 확인 페이지 연결
  src/views/MyPage/index.tsx
  src/views/MyPage/style.css.ts
  src/views/MyPage/types.ts
  src/views/ResultPage/apis.ts
  src/views/ResultPage/hooks/useGetFinalResult.tsx
  src/views/ResultPage/hooks/useGetScreeningResult.tsx
  src/views/ResultPage/index.tsx
Labels: size/L

#158 [Fix] apply 외의 페이지에서 새로고침 경고창 뜨는 에러 해결
  src/views/ApplyPage/index.tsx
Labels: size/S

#161 [Fix] 비번 변경 안되는 에러 해결
  src/views/PasswordPage/index.tsx
Labels: size/XS

#163 [Fix] apply page에 뜨는 에러들 해결
  src/common/components/Select/index.tsx
  src/views/ApplyPage/components/DefaultSection/components/Postcode/index.tsx
  src/views/ApplyPage/components/DefaultSection/index.tsx
  src/views/ApplyPage/index.tsx
  src/views/ApplyPage/types.ts
  src/views/SignedInPage/index.tsx
Labels: size/M

#165 [Feat] 모집 일정에 따른 조건부 렌더링
  src/views/ApplyPage/components/ApplyInfo/index.tsx
  src/views/ApplyPage/index.tsx
  src/views/MainPage/index.tsx
  src/views/MyPage/index.tsx
  src/views/ResultPage/components/FinalResult.tsx
  src/views/ResultPage/components/ScreeningResult.tsx
  src/views/ResultPage/components/style.css.ts
  src/views/ResultPage/index.tsx
  src/views/SignupPage/index.tsx
Labels: size/L

#168 [HotFix] 지원서 페이지에서 체크마크 체크 안되는 에러 해결
  src/views/ApplyPage/components/BottomSection/index.tsx
Labels: size/XS

#169 [Feat] 파일 질문, input 처리
  src/views/ApplyPage/components/CommonSection/index.tsx
  src/views/ApplyPage/components/FileInput/index.tsx
  src/views/ApplyPage/components/LinkInput/index.tsx
  src/views/ApplyPage/components/PartSection/index.tsx
  src/views/ApplyPage/types.ts
Labels: size/M

#173 [Fix] 3차 QA
  src/App.tsx
  src/common/components/Input/InputLine/utils/validateBirthdate.ts
  src/common/components/Layout/Header/index.tsx
  src/common/components/Textarea/Input/index.tsx
  src/common/constants/validationCheck.ts
  src/common/hooks/useDate.tsx
  src/styles/reset.css.ts
  src/views/ApplyPage/components/ApplyInfo/index.tsx
  src/views/ApplyPage/components/FileInput/index.tsx
  src/views/ApplyPage/constant.ts
  src/views/ApplyPage/index.tsx
  src/views/ErrorPage/components/NoMore/index.tsx
  src/views/MainPage/index.tsx
  src/views/MyPage/index.tsx
  src/views/PasswordPage/index.tsx
  src/views/ResultPage/components/ScreeningResult.tsx
  src/views/ResultPage/index.tsx
  src/views/SignInPage/style.css.ts
  src/views/SignupPage/index.tsx
  src/views/dialogs/SessionExpiredDialog/index.tsx
Labels: size/L

#176 [Fix] 지원서 확인 기간 늘리기
  src/common/hooks/useDate.tsx
Labels: size/S

#181 [Feat] 파트 이름 하드 코딩 지우기
  src/views/ApplyPage/components/PartSection/index.tsx
  src/views/ApplyPage/constant.ts
  src/views/ApplyPage/index.tsx
Labels: size/S

#183 [HotFix] 지원서 날짜 수정
  src/views/ApplyPage/components/ApplyInfo/index.tsx
Labels: size/XS

#185 [HotFix] 4차 QA 바로바로 고치기
  src/common/assets/.gitkeep
  src/common/assets/MakersLogo.tsx
  src/common/components/Input/InputTheme.tsx
  src/common/components/Layout/Header/index.tsx
  src/styles/theme.css.ts
  src/views/ApplyPage/components/ApplyHeader/index.tsx
  src/views/ApplyPage/components/FileInput/style.css.ts
  src/views/ApplyPage/index.tsx
Labels: size/M

#187 [Fix] 4.5치 QA 고치기
  src/App.tsx
  src/common/components/Callout/index.tsx
  src/common/components/Callout/style.css.ts
  src/styles/theme.css.ts
  src/views/ResultPage/assets/imgMakersLogo.png
  src/views/ResultPage/assets/imgMakersLogo.webp
  src/views/ResultPage/assets/imgSoptLogo.png
  src/views/ResultPage/assets/imgSoptLogo.webp
  src/views/ResultPage/components/FinalResult.tsx
  src/views/ResultPage/components/ScreeningResult.tsx
  src/views/ResultPage/components/style.css.ts
  src/views/dialogs/SubmitDialog/style.css.ts
  src/views/dialogs/style.css.ts
Labels: size/L

#190 [Fix] 이메일 입력 시 메일 로직 초기화
  src/common/components/Input/InputTheme.tsx
  src/common/hooks/useScrollToHash.ts
  src/views/ApplyPage/index.tsx
Labels: size/S

#192 [Refactor] 폴더 구조 통일
  src/common/components/Checkbox/components/Contentbox/index.tsx
  src/common/components/Checkbox/components/Contentbox/style.css.ts
  src/common/components/Input/components/Description/index.tsx
  src/common/components/Input/components/Description/style.css.ts
  src/common/components/Input/components/InputButton/index.tsx
  src/common/components/Input/components/InputButton/style.css.ts
  src/common/components/Input/components/InputButton/types.ts
  src/common/components/Input/components/InputLine/index.tsx
  src/common/components/Input/components/InputLine/style.css.ts
  src/common/components/Input/components/InputLine/utils/formatBirthdate.ts
  src/common/components/Input/components/InputLine/utils/formatPhoneNumber.ts
  src/common/components/Input/components/InputLine/utils/validateBirthdate.ts
  src/common/components/Input/components/InputLine/utils/validatePasswordConfirm.ts
  src/common/components/Input/components/InputTheme/index.tsx
  src/common/components/Input/components/TextBox/index.tsx
  src/common/components/Input/components/TextBox/style.css.ts
  src/common/components/Input/components/Timer/index.tsx
  src/common/components/Input/components/Timer/style.css.ts
  src/common/components/Input/components/Timer/types.ts
  src/common/components/Input/components/Timer/utils/formatTimer.ts
  src/common/components/Input/hooks/useMutateCheckCode.tsx
  src/common/components/Input/hooks/useMutateCheckUser.tsx
  src/common/components/Input/hooks/useMutateSendCode.tsx
  src/common/components/Input/index.tsx
  src/common/components/Input/types.ts
  src/common/components/Layout/components/Footer/constants.tsx
  src/common/components/Layout/components/Footer/icons/IconArrowRight.tsx
  src/common/components/Layout/components/Footer/icons/IconFacebook.tsx
  src/common/components/Layout/components/Footer/icons/IconInstagram.tsx
  src/common/components/Layout/components/Footer/icons/IconKakaotalk.tsx
  src/common/components/Layout/components/Footer/icons/IconMail.tsx
  src/common/components/Layout/components/Footer/icons/IconYoutube.tsx
  src/common/components/Layout/components/Footer/index.tsx
  src/common/components/Layout/components/Footer/style.css.ts
  src/common/components/Layout/components/Header/MenuItem/index.tsx
  src/common/components/Layout/components/Header/MenuItem/style.css.ts
  src/common/components/Layout/components/Header/contants.ts
  src/common/components/Layout/components/Header/index.tsx
  src/common/components/Layout/components/Header/style.css.ts
  src/common/components/Layout/index.tsx
  src/common/components/Radio/components/Container/index.tsx
  src/common/components/Radio/components/Container/style.css.ts
  src/common/components/Radio/components/ErrorMessage/index.tsx
  src/common/components/Radio/components/ErrorMessage/style.css.ts
  src/common/components/Radio/components/Option/index.tsx
  src/common/components/Radio/components/Option/style.css.ts
  src/common/components/Radio/index.tsx
  src/common/components/Textarea/components/Input/index.tsx
  src/common/components/Textarea/components/Input/style.css.ts
  src/common/components/Textarea/components/Label/index.tsx
  src/common/components/Textarea/components/Label/style.css.ts
  src/common/components/Textarea/index.tsx
  src/common/constants/validationCheck.ts
  src/views/ApplyPage/components/BottomSection/index.tsx
  src/views/PasswordPage/components/PasswordForm/index.tsx
  src/views/SignupPage/components/SignupForm/index.tsx
Labels: size/L

#196 [Feat] 비밀번호 재설정 완료 dialog 붙이기
  src/views/PasswordPage/components/PasswordForm/index.tsx
  src/views/PasswordPage/hooks/useMutateChangePassword.tsx
  src/views/dialogs/CompleteDialog/index.tsx
Labels: size/M

#197 [Feat] amplitude로 사용자 트래킹 하기
  README.md
  package.json
  src/App.tsx
  src/common/components/Input/components/InputTheme/index.tsx
  src/common/components/Layout/components/Header/index.tsx
  src/views/ApplyPage/index.tsx
  src/views/ErrorPage/components/NoMore/index.tsx
  src/views/ErrorPage/index.tsx
  src/views/MyPage/index.tsx
  src/views/PasswordPage/components/PasswordForm/index.tsx
  src/views/SignInPage/components/SignInForm/index.tsx
  src/views/SignInPage/components/SignInInfo/index.tsx
  src/views/SignInPage/hooks/useMutateSignIn.tsx
  src/views/SignInPage/types.ts
  src/views/SignedInPage/index.tsx
  src/views/SignupPage/components/SignupForm/index.tsx
  src/views/dialogs/SessionExpiredDialog/index.tsx
  src/views/dialogs/SubmitDialog/index.tsx
  yarn.lock
Labels: size/L

#200 [Fix] 폼 완료 안 했는데 제출되는 에러 해결
  src/views/ApplyPage/index.tsx
Labels: size/XS

#201 [Fix] 파일 + 버튼 클릭 시 아무런 액션 발생 안 하는 에러 해결
  src/views/ApplyPage/components/FileInput/index.tsx
Labels: size/XS

#205 [Feat] file 첨부 시 required 처리 하기
  src/views/ApplyPage/components/CommonSection/index.tsx
  src/views/ApplyPage/components/FileInput/index.tsx
  src/views/ApplyPage/components/PartSection/index.tsx
Labels: size/S

#206 [Feat] 같은 지원자 회원가입 시도 막기
  src/views/SignupPage/components/SignupForm/index.tsx
  src/views/SignupPage/hooks/useMutateSignUp.tsx
  src/views/dialogs/ExistingApplicantDialog/index.tsx
Labels: size/L

#208 [Refactor] 하드코딩 지우기
  src/common/components/Layout/components/Header/index.tsx
  src/common/hooks/useDate.tsx
  src/common/store/recruitingInfoContext.ts
  src/views/MainPage/index.tsx
  src/views/ResultPage/components/FinalResult.tsx
  src/views/ResultPage/components/ScreeningResult.tsx
  src/views/ResultPage/index.tsx
  src/views/SignInPage/components/SignInInfo/index.tsx
  src/views/SignInPage/index.tsx
Labels: size/L

#209 [Fix] input 값들 max length 테스트 해보기
  src/views/dialogs/SubmitDialog/style.css.ts
Labels: size/XS

#211 [Feat] 학년 Select와 재학 Radio에 졸업 여부 추가 동적으로 설정
  src/views/ApplyPage/components/BottomSection/index.tsx
  src/views/ApplyPage/components/DefaultSection/index.tsx
  src/views/ApplyPage/constant.ts
  src/views/ApplyPage/index.tsx
Labels: size/M

#213 [Feat] amplitude 추적하는 버튼 추가
  src/views/ApplyPage/components/FileInput/index.tsx
  src/views/CompletePage/index.tsx
Labels: size/S

#222 [Refactor] z-index 통합 관리
  src/common/components/Layout/components/Header/style.css.ts
  src/common/components/Select/style.css.ts
  src/common/constants/zIndex.ts
  src/views/ApplyPage/components/ApplyCategory/style.css.ts
  src/views/ApplyPage/components/ApplyHeader/style.css.ts
  src/views/ResultPage/components/style.css.ts
Labels: size/S

#220 [Chore] 워딩 수정
  src/common/constants/validationCheck.ts
  src/views/ApplyPage/components/DefaultSection/index.tsx
  src/views/ApplyPage/constant.ts
Labels: size/S

#218 [Refactor] 하드 코딩 지우기
  src/common/components/Layout/components/Footer/constants.tsx
  src/common/components/Layout/components/Header/contants.ts
  src/common/components/Layout/components/Header/index.tsx
  src/views/ApplyPage/components/ApplyHeader/index.tsx
  src/views/ApplyPage/index.tsx
  src/views/ErrorPage/components/NoMore/index.tsx
  src/views/MainPage/index.tsx
  src/views/PasswordPage/index.tsx
  src/views/ResultPage/index.tsx
  src/views/SignupPage/index.tsx
Labels: size/M

#225 [Fix] 두 번 api 요청 가는 이슈 해결
  src/common/components/Layout/components/Header/index.tsx
  src/common/hooks/useDate.tsx
  src/common/store/recruitingInfoContext.ts
  src/views/ApplyPage/components/ApplyHeader/index.tsx
  src/views/ApplyPage/index.tsx
  src/views/MainPage/index.tsx
  src/views/MyPage/index.tsx
  src/views/PasswordPage/index.tsx
  src/views/ResultPage/components/FinalResult.tsx
  src/views/ResultPage/components/ScreeningResult.tsx
  src/views/ResultPage/index.tsx
  src/views/SignInPage/components/SignInInfo/index.tsx
  src/views/SignInPage/index.tsx
  src/views/SignupPage/index.tsx
Labels: size/L

#226 [Fix] result page 500 에러 해결
  src/views/ResultPage/components/FinalResult.tsx
  src/views/ResultPage/components/ScreeningResult.tsx
Labels: size/XS

#229 [Fix] CompletePage에 isMakers 반영
  src/views/CompletePage/index.tsx
Labels: size/XS

#233 [Refactor] 불필요한 props drilling 제거
  src/common/type/seasonAndGroup.ts
  src/views/PasswordPage/components/PasswordForm/index.tsx
  src/views/PasswordPage/index.tsx
  src/views/ResultPage/components/FinalResult.tsx
  src/views/ResultPage/components/ScreeningResult.tsx
  src/views/SignInPage/components/SignInForm/index.tsx
  src/views/SignInPage/components/SignInInfo/index.tsx
  src/views/SignInPage/index.tsx
  src/views/SignupPage/components/SignupForm/index.tsx
  src/views/SignupPage/index.tsx
Labels: size/M

#246 [Revert] 불필요한 props drilling 제거 revert 하기
  src/common/type/seasonAndGroup.ts
  src/views/PasswordPage/components/PasswordForm/index.tsx
  src/views/PasswordPage/index.tsx
  src/views/ResultPage/components/FinalResult.tsx
  src/views/ResultPage/components/ScreeningResult.tsx
  src/views/SignInPage/components/SignInForm/index.tsx
  src/views/SignInPage/components/SignInInfo/index.tsx
  src/views/SignInPage/index.tsx
  src/views/SignupPage/components/SignupForm/index.tsx
  src/views/SignupPage/index.tsx
Labels: size/M

#247 [Refactor] 불필요한 props drilling 제거
  src/common/type/seasonAndGroup.ts
  src/views/PasswordPage/components/PasswordForm/index.tsx
  src/views/PasswordPage/index.tsx
  src/views/ResultPage/components/FinalResult.tsx
  src/views/ResultPage/components/ScreeningResult.tsx
  src/views/SignInPage/components/SignInForm/index.tsx
  src/views/SignInPage/components/SignInInfo/index.tsx
  src/views/SignInPage/index.tsx
  src/views/SignupPage/components/SignupForm/index.tsx
  src/views/SignupPage/index.tsx
Labels: size/M

#231 [Feat] 토큰 만료 시간 추가
  src/common/apis/tokenInstance.ts
  src/common/components/Layout/components/Header/index.tsx
  src/views/SignInPage/components/SignInForm/index.tsx
  src/views/SignInPage/hooks/useMutateSignIn.tsx
  src/views/dialogs/SessionExpiredDialog/index.tsx
Labels: size/M

#251 [ Fix ] 프로필 사진 규격 제한 제거
  src/common/constants/validationCheck.ts
  src/views/ApplyPage/components/DefaultSection/index.tsx
  src/views/ApplyPage/components/DefaultSection/style.css.ts
Labels: size/S

#239 [Chore] target blank 설정
  README.md
  src/views/ApplyPage/components/ApplyInfo/index.tsx
  src/views/ApplyPage/components/LinkInput/index.tsx
  src/views/ErrorPage/components/NoMore/index.tsx
  src/views/ErrorPage/index.tsx
  src/views/ResultPage/components/ScreeningResult.tsx
  src/views/email/auth.html
  src/views/email/complete.html
Labels: size/S

#249 [Fix] 거주지 임시저장 안 되는 에러 해결
  src/views/ApplyPage/components/DefaultSection/components/Postcode/index.tsx
Labels: size/XS

#237 [ Fix] UI 깜빡깜빡 이슈 해결
  src/common/components/Layout/components/Header/index.tsx
  src/common/components/Select/index.tsx
  src/views/ApplyPage/components/ApplyInfo/index.tsx
Labels: size/M

#253 [Fix] isMakers에 따라 텍스트 조건부 렌더링
  src/common/components/Checkbox/components/Contentbox/style.css.ts
  src/views/ApplyPage/components/BottomSection/index.tsx
Labels: size/S

#241 [Fix] 에러 페이지에서 헤더 없어지는 거 만큼 공백 추가
  src/views/ErrorPage/components/NoMore/index.tsx
  src/views/ErrorPage/index.tsx
  src/views/ErrorPage/style.css.ts
Labels: size/M

#254 [Fix] 프로필 이미지 아이콘 배치 깨짐 해결
  src/views/ApplyPage/components/DefaultSection/style.css.ts
Labels: size/XS

#235 [Fix] 지원서 다시보기에서 뒤로가기 안 되는 에러 수정
  src/App.tsx
  src/views/ApplyPage/components/ApplyHeader/index.tsx
  src/views/ApplyPage/hooks/useMutateSubmit.tsx
  src/views/ApplyPage/index.tsx
  src/views/MyPage/index.tsx
  src/views/ReviewPage/index.tsx
  src/views/SignedInPage/index.tsx
  src/views/dialogs/PreventReviewDialog/index.tsx
Labels: size/L

#257 [Fix] 사진 에러 메세지 떠도 draft image 안 사라지는 에러 해결
  src/views/ApplyPage/components/DefaultSection/index.tsx
  src/views/ApplyPage/index.tsx
Labels: size/S

#258 [Feat] GA 붙이기
  index.html
Labels: size/S

#259 [Feat] PR assignee, reviewer 자동으로 채우기
  .github/auto_assign.yml
  .github/workflows/action.yml
Labels: size/M

#256 [Fix] 이메일 템플릿 레이아웃 깨짐 해결
  src/views/email/auth.html
Labels: size/L

#261 [Fix] 동적 Index html
  index.html
  makersManifest.webmanifest
  package.json
  public/maekrsOg.png
  public/makers-touch-icon.png
  public/makersFavicon.ico
  public/makersIcon.svg
  public/makers_192.png
  public/makers_512.png
  src/App.tsx
  src/common/components/Layout/index.tsx
  src/views/ApplyPage/components/BottomSection/index.tsx
  yarn.lock
Labels: size/L

#262 [Fix] 최대글자수에 따라 textArea 높이 동적 설정
  src/common/components/Textarea/components/Input/index.tsx
  src/common/components/Textarea/components/Input/style.css.ts
  src/common/components/Textarea/index.tsx
Labels: size/M

#264 [Fix] 인증번호 전송 안 했는데 에러 메세지 뜨는 에러 해결
  src/common/components/Input/components/InputLine/style.css.ts
Labels: size/XS

#268 [Feat] 서류 합불 여부에 따른 my page 지원상태 조건부 렌더링
  src/views/ApplyPage/apis.ts
  src/views/ApplyPage/hooks/useGetDraft.tsx
  src/views/ApplyPage/index.tsx
  src/views/MyPage/apis.ts
  src/views/MyPage/index.tsx
  src/views/ResultPage/hooks/useGetFinalResult.tsx
  src/views/ResultPage/hooks/useGetScreeningResult.tsx
  src/views/ResultPage/types.ts
  src/views/ReviewPage/index.tsx
  src/views/SignedInPage/apis.ts
  src/views/SignedInPage/hooks/useGetMyInfo.tsx
  src/views/SignedInPage/index.tsx
  src/views/SignedInPage/types.ts
Labels: size/L

#271 [Design] 합불페이지에 makers 전용 디자인 추가
  src/common/assets/MakersDarkLogo.tsx
  src/common/components/Layout/components/Header/index.tsx
  src/views/ResultPage/assets/IconMakersLogo.tsx
  src/views/ResultPage/assets/imgMakersLogo.png
  src/views/ResultPage/assets/imgMakersLogo.webp
  src/views/ResultPage/components/FinalResult.tsx
  src/views/ResultPage/components/ScreeningResult.tsx
  src/views/ResultPage/components/style.css.ts
Labels: size/L

#270 [Feat] 파트 안내 메세지 추가
  src/views/ApplyPage/components/CommonSection/index.tsx
  src/views/ApplyPage/components/Info/index.tsx
  src/views/ApplyPage/components/Info/style.css.ts
  src/views/ApplyPage/components/PartSection/index.tsx
Labels: size/L

#274 [Feat] admin을 통해 등록된 placeholder 파싱하여 추가
  src/views/ApplyPage/components/PartSection/index.tsx
  src/views/ApplyPage/types.ts
Labels: size/S

#277 [Fix] 공통 문항에 placeholder, optional 적용
  src/views/ApplyPage/components/CommonSection/index.tsx
Labels: size/XS

#279 [Feat] 지원완료 이메일 템플릿 수정 및 반응형 추가
  src/views/email/complete.html
Labels: size/L

#281 [Fix] 최종 QA 반영
  src/common/components/Input/components/InputTheme/index.tsx
  src/views/ApplyPage/components/ApplyHeader/style.css.ts
  src/views/ApplyPage/components/BottomSection/index.tsx
  src/views/ApplyPage/components/DefaultSection/index.tsx
  src/views/ApplyPage/types.ts
Labels: size/M

#285 [Feat] 모바일 접속 미지원
  src/App.tsx
Labels: size/XS

#286 [Fix] required dot 멀리 떨어지는 에러 해결
  src/common/components/Textarea/components/Label/style.css.ts
Labels: size/XS

#291 [Fix] 파트 주의사항 text align 맞추기
  src/views/ApplyPage/components/ApplyInfo/index.tsx
  src/views/ApplyPage/components/ApplyInfo/style.css.ts
  src/views/ApplyPage/components/Info/index.tsx
  src/views/ApplyPage/constant.ts
Labels: size/M

#292 [Feat] FileInput textarea height sm로 만들기
  src/common/components/Textarea/components/Input/index.tsx
  src/common/components/Textarea/index.tsx
  src/views/ApplyPage/components/CommonSection/index.tsx
  src/views/ApplyPage/components/PartSection/index.tsx
Labels: size/S

#297 [Fix] min width 수정
  src/common/components/Layout/components/Header/style.css.ts
  src/common/components/Layout/style.css.ts
Labels: size/XS

#300 [Fix] 공통질문에서 0자 입력 시 textarea 뜨는 에러 해결
  src/views/ApplyPage/components/CommonSection/index.tsx
Labels: size/XS

#307 [Fix] 사파리 - navigate(0) 작동 되지 않는 이슈 해결
  src/common/components/Layout/components/Header/index.tsx
  src/views/CompletePage/index.tsx
  src/views/SignInPage/hooks/useMutateSignIn.tsx
Labels: size/S

#308 [Fix] 사파리 - 이메일 인증 보낼 시 input 너비 증가되는 에러 해결
  src/common/components/Input/components/InputTheme/index.tsx
Labels: size/XS

#311 [Fix] 페이지 벗어나 있으면 타이머 안 움직이는 에러 해결
  src/common/components/Input/components/Timer/index.tsx
Labels: size/M

#310 [Feat] chrome 브라우저 권장 alert
  src/common/hooks/useCheckBrowser.ts
  src/views/ApplyPage/index.tsx
Labels: size/S

#313 [Fix] 지원서 페이지 500 에러 해결
  src/views/ApplyPage/components/Info/index.tsx
Labels: size/XS

#316 [Chore] 서류 합격 페이지에 들어갈 구글폼 링크 env 처리
  src/views/ResultPage/components/ScreeningResult.tsx
Labels: size/XS

#317 [Fix] 지원 안했으면 결과 페이지 막기
  src/views/ResultPage/index.tsx
Labels: size/S

#320 [Fix] 파일 업로드 하는 동안 새로운 파일 업로드 못하도록 막기
  src/views/ApplyPage/components/FileInput/index.tsx
Labels: size/XS

#323 [Chore] 문구 수정
  src/views/ApplyPage/components/BottomSection/index.tsx
Labels: size/XS

#325 [Chore] 문구 재수정
  src/views/ApplyPage/components/BottomSection/index.tsx
  src/views/ApplyPage/constant.ts
Labels: size/XS

#321 [Deploy] 정말 최종 배포
  src/App.tsx
  src/common/components/Input/components/InputTheme/index.tsx
  src/common/components/Input/components/Timer/index.tsx
  src/common/components/Layout/components/Header/index.tsx
  src/common/components/Layout/components/Header/style.css.ts
  src/common/components/Layout/style.css.ts
  src/common/components/Textarea/components/Input/index.tsx
  src/common/components/Textarea/components/Label/index.tsx
  src/common/components/Textarea/components/Label/style.css.ts
  src/common/components/Textarea/index.tsx
  src/common/constants/validationCheck.ts
  src/common/hooks/useCheckBrowser.ts
  src/views/ApplyPage/components/ApplyInfo/index.tsx
  src/views/ApplyPage/components/ApplyInfo/style.css.ts
  src/views/ApplyPage/components/BottomSection/index.tsx
  src/views/ApplyPage/components/CommonSection/index.tsx
  src/views/ApplyPage/components/FileInput/index.tsx
  src/views/ApplyPage/components/Info/index.tsx
  src/views/ApplyPage/components/PartSection/index.tsx
  src/views/ApplyPage/constant.ts
  src/views/ApplyPage/index.tsx
  src/views/CompletePage/index.tsx
  src/views/ResultPage/components/ScreeningResult.tsx
  src/views/ResultPage/index.tsx
  src/views/SignInPage/hooks/useMutateSignIn.tsx
Labels: size/L

#327 [Fix] 모바일 알럿 코드 useEffect로 감싸주기
  src/App.tsx
Labels: size/S

#329 [Fix] 이메일 인증 오류
  src/common/components/Input/components/InputTheme/index.tsx
  src/common/components/Input/hooks/useMutateCheckCode.tsx
Labels: size/S
