Repository sopt-makers/sopt-recruiting-frontend, pull requests merged in 2024-10, with the labels that each got.

#452 [Feat] browserslist 추가
  index.html
  package.json
  src/App.tsx
  src/views/UnsupportedPage/index.tsx
  src/views/UnsupportedPage/supportedBrowsers.ts
  src/views/UnsupportedPage/utils/checkBrowser.ts
  yarn.lock
Labels: size/L

#464 [Design] 지원 안 되는 브라우저 안내 페이지 퍼블리싱
  src/common/assets/NowsoptLogo.tsx
  src/common/assets/SoptLogo.tsx
  src/common/components/Layout/components/Header/index.tsx
  src/views/UnsupportedPage/assets/ChromeIcon.tsx
  src/views/UnsupportedPage/assets/EdgeIcon.tsx
  src/views/UnsupportedPage/assets/FirefoxIcon.tsx
  src/views/UnsupportedPage/assets/SafariIcon.tsx
  src/views/UnsupportedPage/index.tsx
  src/views/UnsupportedPage/style.css.ts
Labels: size/XXL

#465 [Feat] 지원 안 되는 브라우저 안내 페이지 pre render 하기
  .gitignore
  index.html
  package.json
  public/unsupported.css
  src/App.tsx
  src/views/UnsupportedPage/index.tsx
  src/views/UnsupportedPage/pre-render.tsx
  src/views/UnsupportedPage/utils/checkBrowser.ts
  vite.config.ts
Labels: size/XL

#466 [Refactor] lottie-react 재도입 및 patch를 이용한 번들 사이즈 감소
  README.md
  package.json
  patches/lottie-react+2.4.0.patch
  src/views/loadings/BigLoding/index.tsx
  src/views/loadings/ButtonLoading/index.tsx
  src/views/loadings/Lottie/index.tsx
  src/views/loadings/SmallLoading/index.tsx
  src/views/loadings/SmallLoading/style.css.ts
  yarn.lock
Labels: size/L

#453 [Feat] MSW 도입
  package.json
  public/mockServiceWorker.js
  src/App.tsx
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
  tsconfig.json
  yarn.lock
Labels: size/XL
