Repository sopt-makers/sopt-recruiting-frontend, pull requests merged in 2024-05, with the labels that each got.

#4 [Init] path alias 설정
  tsconfig.json
  vite.config.ts
Labels: size/M

#7 [Init] ESLint, Prettier 설정
  .eslintrc.cjs
  .prettierrc.json
  package.json
  src/App.tsx
  src/main.tsx
  src/pages/ApplyPage.tsx
  src/pages/CompletePage.tsx
  src/pages/MainPage.tsx
  src/pages/MyPage.tsx
  src/pages/PasswordPage.tsx
  src/pages/ResultPage.tsx
  src/pages/ReviewPage.tsx
  src/pages/SignupPage.tsx
  src/views/MainPage/style.css.ts
  vite.config.ts
  yarn.lock
Labels: size/XXL

#6 [Init] css 초기세팅
  package.json
  src/App.tsx
  src/common/components/.gitkeep
  src/common/components/Layout/index.tsx
  src/styles/.gitkeep
  src/styles/reset.css.ts
  src/styles/theme.css.ts
  src/views/MainPage/style.css.ts
  yarn.lock
Labels: size/L

#8 [Init] 메타데이터 설정
  README.md
  index.html
  manifest.webmanifest
  package.json
  public/apple-touch-icon.png
  public/favicon.ico
  public/icon-192.png
  public/icon-512.png
  public/icon.svg
  public/imgOg.png
  public/vite.svg
  src/App.tsx
  src/styles/reset.css.ts
  src/styles/theme.css.ts
  src/views/MainPage/style.css.ts
  yarn.lock
Labels: size/L
