Repository sopt-makers/sopt-recruiting-frontend, pull requests merged in 2024-06, with the labels that each got.

#24 [Design] Dialog 공통 컴포넌트 생성
  index.html
  src/common/components/Dialog/index.tsx
  src/common/components/Dialog/style.css.ts
Labels: size/M

#20 [Design] Radio 공통 컴포넌트 생성
  src/common/components/Radio/index.tsx
  src/common/components/Radio/style.css.ts
Labels: size/M

#22 [Design] Callout 공통 컴포넌트 생성
  src/common/components/Callout/index.tsx
  src/common/components/Callout/style.css.ts
Labels: size/M

#23 [Design] Button 공통 컴포넌트 생성
  src/common/components/Button/index.tsx
  src/common/components/Button/style.css.ts
Labels: size/L

#28 [Fix] eslint-import-resolver-typescript 설치 및 세팅
  .eslintrc.cjs
  package.json
  yarn.lock
Labels: size/M

#26 [Feat] Input 공통 컴포넌트 구현
  package.json
  src/common/components/Input/constants.ts
  src/common/components/Input/index.tsx
  src/common/components/Input/style.css.ts
  src/common/components/Input/types.ts
  src/pages/ApplyPage.tsx
  src/pages/MainPage.tsx
  src/styles/theme.css.ts
  src/views/MainPage/style.css.ts
  yarn.lock
Labels: size/L

#27 [Feat] SelectBox 공통 컴포넌트 구현
  src/common/components/Input/style.css.ts
  src/common/components/Input/types.ts
  src/common/components/Select/index.tsx
  src/common/components/Select/style.css.ts
  src/common/components/Select/type.ts
  src/common/constants/.gitkeep
  src/common/constants/defaultValues.ts
  src/common/constants/styleValues.ts
  src/pages/ApplyPage.tsx
Labels: size/L

#33 [Merge] feat/#15_input => develop
  src/common/components/Input/style.css.ts
  src/common/components/Input/types.ts
  src/common/components/Select/index.tsx
  src/common/components/Select/style.css.ts
  src/common/components/Select/type.ts
  src/common/constants/.gitkeep
  src/common/constants/defaultValues.ts
  src/common/constants/styleValues.ts
  src/pages/ApplyPage.tsx
Labels: size/L

#34 [Design] Radio 공통 컴포넌트 에러 기능 추가
  src/common/components/Radio/Container/index.tsx
  src/common/components/Radio/Container/style.css.ts
  src/common/components/Radio/ErrorMessage/index.tsx
  src/common/components/Radio/ErrorMessage/style.css.ts
  src/common/components/Radio/Option/index.tsx
  src/common/components/Radio/Option/style.css.ts
  src/common/components/Radio/index.tsx
Labels: size/L

#36 [Refactor] 간단 작업 처리
  src/App.tsx
  src/common/components/Button/style.css.ts
  src/common/components/Callout/style.css.ts
  src/common/components/Checkbox/Contentbox/style.css.ts
  src/common/components/Checkbox/style.css.ts
  src/common/components/Dialog/style.css.ts
  src/common/components/Radio/Container/style.css.ts
  src/common/components/Radio/ErrorMessage/style.css.ts
  src/common/components/Radio/Option/style.css.ts
  src/common/components/Textarea/Input/index.tsx
  src/common/components/Textarea/Input/style.css.ts
  src/common/components/Textarea/Label/index.tsx
  src/common/components/Textarea/Label/style.css.ts
  src/common/components/Textarea/TextareaHeader/index.tsx
  src/common/components/Textarea/index.tsx
Labels: size/L

#40 [Design] Footer 구현
  src/common/components/Layout/Footer/constants.tsx
  src/common/components/Layout/Footer/icons/IconArrowRight.tsx
  src/common/components/Layout/Footer/icons/IconFacebook.tsx
  src/common/components/Layout/Footer/icons/IconInstagram.tsx
  src/common/components/Layout/Footer/icons/IconKakaotalk.tsx
  src/common/components/Layout/Footer/icons/IconMail.tsx
  src/common/components/Layout/Footer/icons/IconYoutube.tsx
  src/common/components/Layout/Footer/index.tsx
  src/common/components/Layout/Footer/style.css.ts
  src/common/components/Layout/index.tsx
Labels: size/L

#38 [Design] Header 구현
  src/App.tsx
  src/common/assets/NowsoptLogo.tsx
  src/common/components/Layout/Header/MenuItem/index.tsx
  src/common/components/Layout/Header/MenuItem/style.css.ts
  src/common/components/Layout/Header/contants.ts
  src/common/components/Layout/Header/index.tsx
  src/common/components/Layout/Header/style.css.ts
  src/common/components/Layout/index.tsx
  src/common/components/Layout/style.css.ts
  src/pages/MainPage.tsx
Labels: size/L

#41 [Design] 지원하기(/) 페이지 퍼블리싱
  src/App.tsx
  src/common/components/Callout/style.css.ts
  src/common/components/Input/index.tsx
  src/common/components/Layout/Header/style.css.ts
  src/common/components/Layout/index.tsx
  src/common/components/Layout/style.css.ts
  src/common/components/Title/index.tsx
  src/common/components/Title/style.css.ts
  src/pages/MainPage.tsx
  src/views/ApplyPage/index.tsx
  src/views/ApplyPage/style.css.ts
  src/views/CompletePage/index.tsx
  src/views/CompletePage/style.css.ts
  src/views/MainPage/index.tsx
  src/views/MainPage/style.css.ts
  src/views/MyPage/index.tsx
  src/views/MyPage/style.css.ts
  src/views/PasswordPage/index.tsx
  src/views/PasswordPage/style.css.ts
  src/views/ResultPage/index.tsx
  src/views/ResultPage/style.css.ts
  src/views/ReviewPage/index.tsx
  src/views/ReviewPage/style.css.ts
  src/views/SignupPage/index.tsx
  src/views/SignupPage/style.css.ts
Labels: size/L

#43 [Feat] TextBox 내부 Timer 구현
  src/common/components/Input/Description/index.tsx
  src/common/components/Input/Description/style.css.ts
  src/common/components/Input/InputButton/index.tsx
  src/common/components/Input/InputLine/index.tsx
  src/common/components/Input/InputLine/style.css.ts
  src/common/components/Input/TextBox/index.tsx
  src/common/components/Input/TextBox/style.css.ts
  src/common/components/Input/Timer/index.tsx
  src/common/components/Input/Timer/style.css.ts
  src/common/components/Input/Timer/utils/formatTimer.ts
  src/common/components/Input/index.tsx
  src/common/components/Input/style.css.ts
  src/common/components/Input/types.ts
  src/common/utils/.gitkeep
  src/views/ApplyPage/index.tsx
  src/views/MainPage/index.tsx
Labels: size/XL

#46 [Design] 마이페이지 퍼블리싱
  src/common/components/Layout/Header/style.css.ts
  src/views/MyPage/components/.gitkeep
  src/views/MyPage/hooks/.gitkeep
  src/views/MyPage/index.tsx
  src/views/MyPage/style.css.ts
Labels: size/M

#47 [Design] 결과 확인 페이지 퍼블리싱
  package.json
  src/App.tsx
  src/common/components/Layout/Header/style.css.ts
  src/common/components/Layout/index.tsx
  src/common/components/Layout/style.css.ts
  src/common/store/themeContext.ts
  src/styles/theme.css.ts
  src/views/ResultPage/assets/imgLogo.png
  src/views/ResultPage/assets/imgLogo.webp
  src/views/ResultPage/components/.gitkeep
  src/views/ResultPage/hooks/.gitkeep
  src/views/ResultPage/index.tsx
  src/views/ResultPage/style.css.ts
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: size/L

#52 [Design] 새 지원서 작성하기 (/sign-up) 퍼블리싱
  src/common/components/Checkbox/Contentbox/index.tsx
  src/common/components/Checkbox/index.tsx
  src/common/components/Input/types.ts
  src/views/SignupPage/constant.ts
  src/views/SignupPage/index.tsx
  src/views/SignupPage/style.css.ts
Labels: size/L

#53 [Design] 비밀번호 재설정하기 페이지 (/password) 퍼블리싱
  src/App.tsx
  src/common/components/Input/InputTheme.tsx
  src/common/components/Layout/index.tsx
  src/common/components/Layout/style.css.ts
  src/views/MainPage/components/.gitkeep
  src/views/PasswordPage/components/.gitkeep
  src/views/PasswordPage/hooks/.gitkeep
  src/views/PasswordPage/index.tsx
  src/views/PasswordPage/style.css.ts
  src/views/ResultPage/index.tsx
  src/views/SignupPage/components/.gitkeep
  src/views/SignupPage/index.tsx
Labels: size/L

#66 [Chore] Test 코드 제거
  src/views/ApplyPage/index.tsx
Labels: size/XS

#63 [Fix] body에 background 넣기
  src/App.tsx
Labels: size/XS

#57 [Design] 지원서 (/apply) 페이지 form 제외 퍼블리싱
  src/views/ApplyPage/components/ApplyCategory/constant.ts
  src/views/ApplyPage/components/ApplyCategory/index.tsx
  src/views/ApplyPage/components/ApplyCategory/style.css.ts
  src/views/ApplyPage/components/ApplyHeader/index.tsx
  src/views/ApplyPage/components/ApplyHeader/style.css.ts
  src/views/ApplyPage/components/ApplyInfo/index.tsx
  src/views/ApplyPage/components/ApplyInfo/style.css.ts
  src/views/ApplyPage/constant.ts
  src/views/ApplyPage/hooks/.gitkeep
  src/views/ApplyPage/hooks/useIntersectionObserver.ts
  src/views/ApplyPage/hooks/useScrollToHash.ts
  src/views/ApplyPage/index.tsx
  src/views/ApplyPage/style.css.ts
Labels: size/L

#62 [Refactor] Button 공통 컴포넌트를 이용하여 Link를 사용할 수 있게 하기
  src/common/components/Button/index.tsx
  src/common/components/Button/style.css.ts
  src/views/CompletePage/index.tsx
Labels: size/M

#68 [Design] 이메일 템플릿 퍼블리싱
  src/views/email/auth.html
  src/views/email/complete.html
  src/views/email/iconLogo.svg
Labels: size/L

#70 [Design] 지원서(/apply) form 내부 구현
  src/common/components/Select/style.css.ts
  src/common/constants/defaultValues.ts
  src/common/constants/policy.ts
  src/views/ApplyPage/components/ApplyHeader/index.tsx
  src/views/ApplyPage/components/BottomSection/index.tsx
  src/views/ApplyPage/components/BottomSection/style.css.ts
  src/views/ApplyPage/components/CommonSection/constants.ts
  src/views/ApplyPage/components/CommonSection/index.tsx
  src/views/ApplyPage/components/CommonSection/style.css.ts
  src/views/ApplyPage/components/DefaultSection/constants.ts
  src/views/ApplyPage/components/DefaultSection/icons/IconUser.tsx
  src/views/ApplyPage/components/DefaultSection/index.tsx
  src/views/ApplyPage/components/DefaultSection/style.css.ts
  src/views/ApplyPage/components/PartSection/constants.ts
  src/views/ApplyPage/components/PartSection/index.tsx
  src/views/ApplyPage/components/PartSection/style.css.ts
  src/views/ApplyPage/components/PartSection/types.ts
  src/views/ApplyPage/constant.ts
  src/views/ApplyPage/hooks/useIntersectionObserver.ts
  src/views/ApplyPage/index.tsx
  src/views/ApplyPage/style.css.ts
  src/views/MainPage/index.tsx
  src/views/ResultPage/index.tsx
  src/views/SignupPage/index.tsx
Labels: size/XL

#76 [Fix] Button 텍스트 부분 제외 클릭 안 되는 에러 수정
  src/common/components/Button/index.tsx
  src/common/components/Button/style.css.ts
Labels: size/S

#78 [Fix] Textarea에서 required 점이 아래로 내려가는 에러 해결
  src/common/components/Textarea/Label/index.tsx
  src/common/components/Textarea/Label/style.css.ts
Labels: size/S
