Repository sopt-makers/sopt-recruiting-frontend, pull requests merged in 2024-09, with the labels that each got.

#439 [Feat] 테스트 코드 초기 세팅
  .eslintrc.cjs
  README.md
  package.json
  src/tests/setupTests.ts
  src/tests/test-utils.tsx
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: size/XL

#443 [Chore] reviewer에 주용이 추가
  .github/auto_assign.yml
Labels: size/XS

#445 [Refactor] token 필요없는 fetch custom hook 만들기
  src/common/apis/getRecruitingInfo.ts
  src/common/apis/instance.ts
  src/common/components/Input/apis.ts
  src/views/PasswordPage/apis.ts
  src/views/SignInPage/apis.ts
  src/views/SignupPage/apis.ts
Labels: size/L

#441 [Refactor] ApplyPage 로직 분리 - 1
  src/App.tsx
  src/common/hooks/useDialog.tsx
  src/common/hooks/useEventListener.tsx
  src/views/ApplyPage/components/ApplyCategory/index.tsx
  src/views/ApplyPage/components/ApplyHeader/index.tsx
  src/views/ApplyPage/components/ApplyInfo/index.tsx
  src/views/ApplyPage/components/BottomSection/index.tsx
  src/views/ApplyPage/components/CommonSection/index.tsx
  src/views/ApplyPage/components/DefaultSection/index.tsx
  src/views/ApplyPage/components/PartSection/index.tsx
  src/views/ApplyPage/hooks/useBeforeExitPageAlert.tsx
  src/views/ApplyPage/index.tsx
  src/views/PasswordPage/components/PasswordForm/index.tsx
  src/views/ReviewPage/index.tsx
  src/views/SignupPage/components/SignupForm/index.tsx
Labels: size/L

#448 [Feat] env 개발 환경 분리하기
  .gitignore
  package.json
Labels: size/S

#455 [Feat] 환경변수를 활용한 동적 메타태그 구현
  index.html
  package.json
  src/App.tsx
  src/common/components/Layout/components/Head/index.tsx
  src/common/components/Layout/index.tsx
  src/common/hooks/useDate.tsx
  src/views/CompletePage/index.tsx
  yarn.lock
Labels: size/L

#450 [Refactor] fetch instance 기능 보강
  src/common/apis/fetcher.ts
  src/common/apis/getRecruitingInfo.ts
  src/common/apis/instance.ts
  src/common/components/Input/apis.ts
  src/common/components/Input/hooks/useMutateCheckCode.tsx
  src/common/components/Input/hooks/useMutateCheckUser.tsx
  src/common/components/Input/hooks/useMutateSendCode.tsx
  src/common/hooks/useDate.tsx
  src/common/hooks/useGetRecruitingInfo.tsx
  src/views/PasswordPage/apis.ts
  src/views/PasswordPage/hooks/useMutateChangePassword.tsx
  src/views/SignInPage/apis.ts
  src/views/SignInPage/hooks/useMutateSignIn.tsx
  src/views/SignupPage/apis.ts
  src/views/SignupPage/hooks/useMutateSignUp.tsx
Labels: size/L
