Repository sopt-makers/sopt-recruiting-frontend, pull requests merged in 2025-08, with the labels that each got.

#498 37기 모집 전 배포
  src/common/components/Input/components/InputTheme/index.tsx
  src/common/components/Layout/components/Head/index.tsx
  src/common/components/Layout/components/Header/Nav/MenuList/index.tsx
  src/common/components/Layout/components/Header/index.tsx
  src/common/constants/mode.ts
  src/common/hooks/useDate.tsx
  src/constants/mode.ts
  src/contexts/RecruitingInfoProvider.tsx
  src/views/ApplyPage/components/ApplyHeader/index.tsx
  src/views/ApplyPage/components/BottomSection/index.tsx
  src/views/ApplyPage/components/DefaultSection/index.tsx
  src/views/ApplyPage/constant.ts
  src/views/ApplyPage/index.tsx
  src/views/CompletePage/index.tsx
  src/views/MyPage/index.tsx
  src/views/PasswordPage/index.tsx
  src/views/ResultPage/components/FinalResult.tsx
  src/views/ResultPage/components/ScreeningResult.tsx
  src/views/ResultPage/index.tsx
  src/views/ReviewPage/index.tsx
  src/views/SignInPage/components/SignInForm/index.tsx
  src/views/SignInPage/components/SignInInfo/index.tsx
  src/views/SignInPage/index.tsx
  src/views/SignupPage/components/SignupForm/index.tsx
  src/views/SignupPage/index.tsx
  src/views/UnsupportedPage/index.tsx
Labels: size/L

#499 hotfix 배포
  src/common/components/Input/components/InputTheme/index.tsx
  src/views/SignInPage/components/SignInForm/index.tsx
  src/views/SignupPage/components/SignupForm/index.tsx
Labels: size/S

#500 인터뷰 기간 수정 후 재배포
  src/views/ResultPage/components/ScreeningResult.tsx
Labels: size/S

#501 [FIX] 서류결과 인터뷰일정 서버에서 받아온 값으로 처리
  src/views/ResultPage/components/ScreeningResult.tsx
Labels: size/S

#502 Prod 배포
  package.json
  patches/lottie-react+2.4.1.patch
  public/mockServiceWorker.js
  src/views/ResultPage/components/ScreeningResult.tsx
  yarn.lock
Labels: size/XXL

#506 37기 메인 컬러 main 반영
  src/styles/theme.css.ts
Labels: size/S

#507 37기 SOPT 로고 변경
  public/favicon.ico
  public/icon.svg
  public/logo_sopt.svg
  src/common/assets/SoptLogo.tsx
Labels: size/L

#511 main 배포
  src/views/dialogs/style.css.ts
Labels: size/XS

#512 main 배포
  src/views/dialogs/DraftDialog/index.tsx
  src/views/dialogs/style.css.ts
Labels: size/XS

#513 버튼 스타일 이슈 해결
  src/views/dialogs/SubmitDialog/index.tsx
  src/views/dialogs/style.css.ts
Labels: size/XS

#514 hotfix 배포
  src/views/dialogs/DraftDialog/index.tsx
Labels: size/XS

#518 main 배포
  README.md
  package.json
  src/views/ResultPage/assets/IconSoptRecrutingLogo.tsx
  src/views/ResultPage/components/FinalResult.tsx
  src/views/ResultPage/components/ScreeningResult.tsx
Labels: size/L

#520 main 배포
  src/views/ResultPage/components/FinalResult.tsx
  src/views/ResultPage/components/ScreeningResult.tsx
  src/views/ResultPage/components/style.css.ts
Labels: size/L

#523 main 배포
  README.md
  src/common/components/Layout/components/Head/index.tsx
  src/common/components/Layout/components/Header/Nav/MenuList/index.tsx
  src/common/components/Layout/components/Header/index.tsx
  src/common/constants/mode.ts
  src/styles/theme.css.ts
  src/views/ApplyPage/components/ApplyHeader/index.tsx
  src/views/ApplyPage/components/BottomSection/index.tsx
  src/views/ApplyPage/components/DefaultSection/index.tsx
  src/views/ApplyPage/constant.ts
  src/views/ApplyPage/index.tsx
  src/views/CompletePage/index.tsx
  src/views/MyPage/index.tsx
  src/views/PasswordPage/index.tsx
  src/views/ResultPage/components/FinalResult.tsx
  src/views/ResultPage/components/ScreeningResult.tsx
  src/views/ResultPage/index.tsx
  src/views/ReviewPage/index.tsx
  src/views/SignInPage/components/SignInInfo/index.tsx
  src/views/SignInPage/index.tsx
  src/views/SignupPage/index.tsx
  src/views/UnsupportedPage/index.tsx
  src/vite-env.d.ts
  vite.config.ts
Labels: size/L
