Repository sopt-makers/sopt-recruiting-frontend, pull requests merged in 2025-07, with the labels that each got.

#485 [Feat] v2 메인 배포
  package.json
  src/__generated__/api-types/RecruitingAnswer.ts
  src/common/apis/fileUpload.ts
  src/common/constants/firebase.ts
  src/common/hooks/useDate.tsx
  src/common/type/recruitingInfo.ts
  src/contexts/RecruitingInfoProvider.tsx
  src/main.tsx
  src/views/ApplyPage/apis.ts
  src/views/ApplyPage/components/ApplyInfo/index.tsx
  src/views/ApplyPage/components/CommonSection/index.tsx
  src/views/ApplyPage/components/DefaultSection/index.tsx
  src/views/ApplyPage/components/FileInput/index.tsx
  src/views/ApplyPage/components/PartSection/index.tsx
  src/views/ApplyPage/hooks/useMutateDraft.tsx
  src/views/ApplyPage/hooks/useMutateSubmit.tsx
  src/views/ApplyPage/index.tsx
  src/views/ApplyPage/types.ts
  src/views/ResultPage/components/ScreeningResult.tsx
  src/views/SignInPage/components/SignInForm/index.tsx
  src/views/SignInPage/hooks/useMutateSignIn.tsx
  vite.config.ts
  yarn.lock
Labels: size/XL

#488 main 배포
  src/views/ApplyPage/constant.ts
Labels: size/XS

#490 main 배포
  src/views/ApplyPage/index.tsx
Labels: bug, size/XS

#491 main 배포
  src/views/ApplyPage/index.tsx
Labels: size/XS

#492 main 배포
  src/views/ApplyPage/index.tsx
Labels: size/XS

#493 [Hotfix] 임시저장 파트명 수정
  src/views/ApplyPage/index.tsx
Labels: size/XS
